version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-name: "org.scala-lang:scala-library"
      - dependency-name: "org.apache.spark:spark-sql_2.12"
      - dependency-name: "org.apache.spark:spark-sql_2.13"
    ignore:
      - dependency-name: "org.scala-lang:scala-library"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
